/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

/**
 *
 * @author Ascalero
 */
public class NewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public NewJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jlTitulo = new javax.swing.JLabel();
        jLNoPreg = new javax.swing.JLabel();
        jlPregEsp = new javax.swing.JLabel();
        jlPregENG = new javax.swing.JLabel();
        jlPregAle = new javax.swing.JLabel();
        jlPregFra = new javax.swing.JLabel();
        jtfpreg1 = new javax.swing.JTextField();
        jtfpreg2 = new javax.swing.JTextField();
        jtfpreg3 = new javax.swing.JTextField();
        jtfpreg4 = new javax.swing.JTextField();
        jcbTyprepreg = new javax.swing.JComboBox();
        jLTypePre = new javax.swing.JLabel();
        paneltipo = new org.jdesktop.swingx.JXPanel();
        jpImaQ = new javax.swing.JPanel();
        jBIQima1 = new javax.swing.JButton();
        jBIQima2 = new javax.swing.JButton();
        jBIQima3 = new javax.swing.JButton();
        jBIQima4 = new javax.swing.JButton();
        jldirIQ1 = new javax.swing.JLabel();
        jldirIQ2 = new javax.swing.JLabel();
        jldirIQ3 = new javax.swing.JLabel();
        jldirIQ4 = new javax.swing.JLabel();
        jlTitCIQ = new javax.swing.JLabel();
        jbAddIQ = new javax.swing.JButton();
        JpanelSTQ1 = new javax.swing.JPanel();
        jbaddNQ = new javax.swing.JButton();
        jRBLikeIt = new javax.swing.JRadioButton();
        jRBPregLibre = new javax.swing.JRadioButton();
        jLTitIm = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jRBBlanco = new javax.swing.JRadioButton();
        jRBMalla = new javax.swing.JRadioButton();
        jRBLibre = new javax.swing.JRadioButton();
        jlInsGrid = new javax.swing.JLabel();
        jBaddQGrid = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListPregs = new javax.swing.JList();
        jltittlepreg = new javax.swing.JLabel();
        jBANE = new javax.swing.JButton();

        setAutoscrolls(true);

        jlTitulo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jlTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlTitulo.setText("Titulo");
        jlTitulo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jlTitulo.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);

        jLNoPreg.setText("Pregunta 1");

        jlPregEsp.setText("jLabel3");

        jlPregENG.setText("jLabel4");

        jlPregAle.setText("jLabel5");

        jlPregFra.setText("jLabel6");

        jtfpreg1.setText("jTextField1");

        jtfpreg2.setText("jTextField2");

        jtfpreg3.setText("jTextField3");

        jtfpreg4.setText("jTextField4");

        jcbTyprepreg.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLTypePre.setText("jLabel7");

        paneltipo.setBorder(javax.swing.BorderFactory.createTitledBorder("Text"));
        paneltipo.setLayout(new java.awt.CardLayout());

        jBIQima1.setText("jButton1");
        jBIQima1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBIQima1ActionPerformed(evt);
            }
        });

        jBIQima2.setText("jButton2");

        jBIQima3.setText("jButton3");

        jBIQima4.setText("jButton4");

        jldirIQ1.setText("jLabel1");

        jldirIQ2.setText("jLabel3");

        jldirIQ3.setText("jLabel4");

        jldirIQ4.setText("jLabel5");

        jlTitCIQ.setText("jLabel6");

        jbAddIQ.setText("jButton5");

        javax.swing.GroupLayout jpImaQLayout = new javax.swing.GroupLayout(jpImaQ);
        jpImaQ.setLayout(jpImaQLayout);
        jpImaQLayout.setHorizontalGroup(
            jpImaQLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpImaQLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpImaQLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpImaQLayout.createSequentialGroup()
                        .addGroup(jpImaQLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jpImaQLayout.createSequentialGroup()
                                .addComponent(jBIQima2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jldirIQ2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jpImaQLayout.createSequentialGroup()
                                .addComponent(jBIQima3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jldirIQ3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jpImaQLayout.createSequentialGroup()
                                .addComponent(jBIQima1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jldirIQ1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpImaQLayout.createSequentialGroup()
                                .addComponent(jBIQima4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jpImaQLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jbAddIQ)
                                    .addComponent(jldirIQ4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpImaQLayout.createSequentialGroup()
                        .addGap(0, 39, Short.MAX_VALUE)
                        .addComponent(jlTitCIQ, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(232, 232, 232))))
        );
        jpImaQLayout.setVerticalGroup(
            jpImaQLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpImaQLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlTitCIQ, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jpImaQLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBIQima1)
                    .addComponent(jldirIQ1))
                .addGap(18, 18, 18)
                .addGroup(jpImaQLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBIQima2)
                    .addComponent(jldirIQ2))
                .addGap(18, 18, 18)
                .addGroup(jpImaQLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBIQima3)
                    .addComponent(jldirIQ3))
                .addGap(18, 18, 18)
                .addGroup(jpImaQLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBIQima4)
                    .addComponent(jldirIQ4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbAddIQ)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        paneltipo.add(jpImaQ, "card3");

        jbaddNQ.setText("Agregar");
        jbaddNQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbaddNQActionPerformed(evt);
            }
        });

        jRBLikeIt.setText("jRadioButton1");

        jRBPregLibre.setText("jRadioButton2");

        jLTitIm.setText("jLabel1");

        javax.swing.GroupLayout JpanelSTQ1Layout = new javax.swing.GroupLayout(JpanelSTQ1);
        JpanelSTQ1.setLayout(JpanelSTQ1Layout);
        JpanelSTQ1Layout.setHorizontalGroup(
            JpanelSTQ1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpanelSTQ1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(JpanelSTQ1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRBPregLibre)
                    .addComponent(jRBLikeIt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 134, Short.MAX_VALUE)
                .addComponent(jbaddNQ, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(98, 98, 98))
            .addGroup(JpanelSTQ1Layout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addComponent(jLTitIm, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        JpanelSTQ1Layout.setVerticalGroup(
            JpanelSTQ1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpanelSTQ1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLTitIm, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(JpanelSTQ1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(JpanelSTQ1Layout.createSequentialGroup()
                        .addComponent(jRBLikeIt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRBPregLibre))
                    .addComponent(jbaddNQ, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(143, Short.MAX_VALUE))
        );

        paneltipo.add(JpanelSTQ1, "card2");

        jRBBlanco.setText("jRadioButton1");

        jRBMalla.setText("jRadioButton2");

        jRBLibre.setText("jRadioButton3");

        jlInsGrid.setText("jLabel1");

        jBaddQGrid.setText("jButton1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRBBlanco)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRBMalla)
                                    .addComponent(jRBLibre))
                                .addGap(67, 67, 67)
                                .addComponent(jBaddQGrid, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(jlInsGrid, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(125, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jlInsGrid)
                .addGap(18, 18, 18)
                .addComponent(jRBBlanco)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jRBMalla)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRBLibre))
                    .addComponent(jBaddQGrid, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE))
                .addContainerGap(155, Short.MAX_VALUE))
        );

        paneltipo.add(jPanel1, "card4");

        jListPregs.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jListPregs);

        jltittlepreg.setText("jLabel3");

        jBANE.setText("jButton1");
        jBANE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBANEActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLTypePre, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jcbTyprepreg, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jlPregENG)
                                            .addComponent(jlPregEsp)
                                            .addComponent(jlPregAle)
                                            .addComponent(jlPregFra))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jtfpreg1)
                                            .addComponent(jtfpreg2)
                                            .addComponent(jtfpreg3)
                                            .addComponent(jtfpreg4, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(paneltipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jLNoPreg))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addComponent(jltittlepreg, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBANE, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE))
                        .addGap(0, 68, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLNoPreg)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlPregEsp)
                            .addComponent(jtfpreg1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jltittlepreg)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlPregENG)
                            .addComponent(jtfpreg2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlPregAle)
                            .addComponent(jtfpreg3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlPregFra)
                            .addComponent(jtfpreg4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jcbTyprepreg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLTypePre, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(paneltipo, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBANE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(51, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbaddNQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbaddNQActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbaddNQActionPerformed

    private void jBIQima1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBIQima1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBIQima1ActionPerformed

    private void jBANEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBANEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBANEActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JpanelSTQ1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JButton jBANE;
    private javax.swing.JButton jBIQima1;
    private javax.swing.JButton jBIQima2;
    private javax.swing.JButton jBIQima3;
    private javax.swing.JButton jBIQima4;
    private javax.swing.JButton jBaddQGrid;
    private javax.swing.JLabel jLNoPreg;
    private javax.swing.JLabel jLTitIm;
    private javax.swing.JLabel jLTypePre;
    private javax.swing.JList jListPregs;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRBBlanco;
    private javax.swing.JRadioButton jRBLibre;
    private javax.swing.JRadioButton jRBLikeIt;
    private javax.swing.JRadioButton jRBMalla;
    private javax.swing.JRadioButton jRBPregLibre;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbAddIQ;
    private javax.swing.JButton jbaddNQ;
    private javax.swing.JComboBox jcbTyprepreg;
    private javax.swing.JLabel jlInsGrid;
    private javax.swing.JLabel jlPregAle;
    private javax.swing.JLabel jlPregENG;
    private javax.swing.JLabel jlPregEsp;
    private javax.swing.JLabel jlPregFra;
    private javax.swing.JLabel jlTitCIQ;
    private javax.swing.JLabel jlTitulo;
    private javax.swing.JLabel jldirIQ1;
    private javax.swing.JLabel jldirIQ2;
    private javax.swing.JLabel jldirIQ3;
    private javax.swing.JLabel jldirIQ4;
    private javax.swing.JLabel jltittlepreg;
    private javax.swing.JPanel jpImaQ;
    private javax.swing.JTextField jtfpreg1;
    private javax.swing.JTextField jtfpreg2;
    private javax.swing.JTextField jtfpreg3;
    private javax.swing.JTextField jtfpreg4;
    private org.jdesktop.swingx.JXPanel paneltipo;
    // End of variables declaration//GEN-END:variables
}
