/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz.FrameEncuestas;

import estructuras.*;
import interfaz.PanelMiembro;
import java.util.ArrayList;
import javax.swing.*;
import javax.swing.WindowConstants;

/**
 *
 * @author Shadow
 */
public class FrameLikeIt extends javax.swing.JFrame {

    private int foo;
    private String strTemp[]=new String[4];
    
    private Survey s;
    private RespEnq re;
    private StructLikeIt strucLikeIt;
    ArrayList <String> datoEnc;
    
    public FrameLikeIt(int foo,Survey s,RespEnq re,ArrayList<String> datoEnc,StructLikeIt forma) {
        this.foo=foo;
        this.s=s;
        this.re=re;
        this.datoEnc=datoEnc;
        this.strucLikeIt=forma;
        
        setTitle(s.getName());
        
        initComponents();
        setIdioma(foo);
        
        setDefaultCloseOperation (WindowConstants.EXIT_ON_CLOSE);
        setLocation(10,20);
        setSize(600, 220);
        setVisible (true);
    }

    public void setIdioma(int foo){
        strTemp[0]="Pregunta"+s.getActual();strTemp[1]="Question"+s.getActual();strTemp[2]="Frage"+s.getActSize();strTemp[3]="Question"+s.getActSize();
        jlNumAsk.setText(strTemp[0]);
        jlAsk.setText(strucLikeIt.getQuest(foo));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rbGroup = new javax.swing.ButtonGroup();
        jlAsk = new javax.swing.JLabel();
        jlNumAsk = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jrb1 = new javax.swing.JRadioButton();
        jrb2 = new javax.swing.JRadioButton();
        jrb3 = new javax.swing.JRadioButton();
        jrb4 = new javax.swing.JRadioButton();
        jrb5 = new javax.swing.JRadioButton();
        jrb6 = new javax.swing.JRadioButton();
        jrb7 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        rbGroup.add(jrb1);
        rbGroup.add(jrb2);
        rbGroup.add(jrb3);
        rbGroup.add(jrb4);
        rbGroup.add(jrb5);
        rbGroup.add(jrb6);
        rbGroup.add(jrb7);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlAsk.setText("jLabel2");

        jlNumAsk.setText("jLabel2");

        jLabel1.setText("jLabel1");

        jrb1.setText("1");

        jrb2.setText("2");

        jrb3.setText("3");

        jrb4.setText("4");

        jrb5.setText("5");

        jrb6.setText("6");
        jrb6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb6ActionPerformed(evt);
            }
        });

        jrb7.setText("7");

        jLabel2.setText("jLabel2");

        strTemp[0]="Siguiente";strTemp[1]="Next";strTemp[2]="Nächste";strTemp[3]="Prochain";
        jButton1.setText(strTemp[foo]);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlNumAsk)
                    .addComponent(jlAsk))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(120, 120, 120)
                                .addComponent(jrb1)
                                .addGap(18, 18, 18)
                                .addComponent(jrb2)
                                .addGap(18, 18, 18)
                                .addComponent(jrb3)
                                .addGap(18, 18, 18)
                                .addComponent(jrb4)
                                .addGap(18, 18, 18)
                                .addComponent(jrb5)
                                .addGap(18, 18, 18)
                                .addComponent(jrb6)
                                .addGap(18, 18, 18)
                                .addComponent(jrb7))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(245, 245, 245)
                                .addComponent(jButton1)))
                        .addContainerGap(147, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(105, 105, 105))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jlNumAsk)
                .addGap(6, 6, 6)
                .addComponent(jlAsk)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrb1)
                    .addComponent(jrb2)
                    .addComponent(jrb3)
                    .addComponent(jrb4)
                    .addComponent(jrb5)
                    .addComponent(jrb6)
                    .addComponent(jrb7))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jrb6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrb6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(select()){
            re.setRLISI(opSelect(), 1);
            if(!s.islast()){
                switch(s.getNext()){
                    case 0:new FrameAskFree(0,s,re,datoEnc,s.getNextStq());break;
                    case 1:new FrameLikeIt(0,s,re,datoEnc,s.getNextLI());break;
                    case 2:new FrameImaQ(0,s,re,datoEnc,s.getNextStIQ());break;
                    case 3:new FrameMouseTraking(0,s,re,datoEnc,s.getNextQG());
                    default:break;
                }
            }else{
                strTemp[0]="Gracias por Participar";strTemp[1]="Write your Answer";
                strTemp[2]="Schreiben Sie Ihre Antwort";strTemp[3]="Ecrivez votre réponse";
                JOptionPane.showMessageDialog(null,strTemp[foo]);
                new PanelMiembro(foo);
            }
            
            this.dispose();
        }else{
            strTemp[0]="Debes de Seleccionar una Opcion";strTemp[1]="You Must select a choise";
            strTemp[2]="Sie müssen eine Wahl";strTemp[3]="Vous devez sélectionner un choix";
            JOptionPane.showMessageDialog(null,strTemp[foo]);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    public boolean select(){
        boolean b=false;
        if(jrb1.isSelected()){b=true;}
        if(jrb2.isSelected()){b=true;}
        if(jrb3.isSelected()){b=true;}
        if(jrb4.isSelected()){b=true;}
        if(jrb5.isSelected()){b=true;}
        if(jrb6.isSelected()){b=true;}
        if(jrb7.isSelected()){b=true;}
        return b;
    }
    
    public int opSelect(){
        int op=0;
        if(jrb1.isSelected()){op=1;}
        if(jrb2.isSelected()){op=2;}
        if(jrb3.isSelected()){op=3;}
        if(jrb4.isSelected()){op=4;}
        if(jrb5.isSelected()){op=5;}
        if(jrb6.isSelected()){op=6;}
        if(jrb7.isSelected()){op=7;}
        return op;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jlAsk;
    private javax.swing.JLabel jlNumAsk;
    private javax.swing.JRadioButton jrb1;
    private javax.swing.JRadioButton jrb2;
    private javax.swing.JRadioButton jrb3;
    private javax.swing.JRadioButton jrb4;
    private javax.swing.JRadioButton jrb5;
    private javax.swing.JRadioButton jrb6;
    private javax.swing.JRadioButton jrb7;
    private javax.swing.ButtonGroup rbGroup;
    // End of variables declaration//GEN-END:variables
}
