/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz.FrameEncuestas;

import estructuras.*;
import interfaz.JPanelConFondo;
import interfaz.PanelMiembro;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.*;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.WindowConstants;

/**
 *
 * @author Shadow
 */
public class FrameMouseTraking extends javax.swing.JFrame implements ActionListener{

    
    private int foo;
    private String strTemp[]=new String[4];
    
    private Survey s;
    private RespEnq re;
    private StructQuestGrid strucGird;
    ArrayList <String> datoEnc;
    
    //<editor-fold defaultstate="collapsed" desc="Variables Menu">
    JMenuBar menuBar;
    JMenu menu;
    JMenuItem menuItem;
    JRadioButtonMenuItem rbMILang[];
    
    //</editor-fold>
    
    public FrameMouseTraking(int foo,Survey s,RespEnq re,ArrayList <String> datos,StructQuestGrid forma) {
        this.foo=foo;
        this.s=s;
        this.re=re;
        this.datoEnc=datos;
        strucGird=forma;
        
        setTitle(s.getName());
        
        initComponents();
        menuCharger();
        setIdioma(foo);
        
        setDefaultCloseOperation (WindowConstants.EXIT_ON_CLOSE);
        setLocation(10,20);
        setSize(700, 640);
        setVisible (true);
    }

    public void setIdioma(int foo){
        this.foo=foo;
        strTemp[0]="Pregunta"+s.getActual();strTemp[1]="Question"+s.getActual();strTemp[2]="Frage"+s.getActSize();strTemp[3]="Question"+s.getActSize();
        jlNumAsk.setText(strTemp[foo]);
        jlAsk.setText(strucGird.getQuest(foo));
        jpMouseT.setImagen(strucGird.getDir());
        
        //idioma en el menu
        strTemp[0]="Idioma";strTemp[1]="Language";strTemp[2]="Sprache";strTemp[3]="langue";
        menu.setText(strTemp[foo]);
        strTemp[0]="Selecciona tu idioma";strTemp[1]="Select your language";strTemp[2]="Wählen Sie Ihre Sprache";strTemp[3]="Choisissez votre langue";
        menuItem.setText(strTemp[foo]);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jpMouseT = new MouseTraking("../../ima/cuadricula.png");
        jlAsk = new javax.swing.JLabel();
        jlNumAsk = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        //new MouseTraking1(s.getNextQG().getDir());
        jpMouseT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nextSurvey();
            }
        });
        jpMouseT.setPreferredSize(new java.awt.Dimension(650, 500));

        javax.swing.GroupLayout jpMouseTLayout = new javax.swing.GroupLayout(jpMouseT);
        jpMouseT.setLayout(jpMouseTLayout);
        jpMouseTLayout.setHorizontalGroup(
            jpMouseTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );
        jpMouseTLayout.setVerticalGroup(
            jpMouseTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        getContentPane().add(jpMouseT, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 650, 500));

        jlAsk.setText("");
        getContentPane().add(jlAsk, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jlNumAsk.setText("");
        getContentPane().add(jlNumAsk, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void nextSurvey(){
        if(!jpMouseT.isEmpty()){
            re.setSIT(jpMouseT.getPoints(),jpMouseT.getClick());
            if(!s.islast()){
                switch(s.getNext()){
                    case 0:new FrameAskFree(foo,s,re,datoEnc,s.getNextStq());break;
                    case 1:new FrameLikeIt(foo,s,re,datoEnc,s.getNextLI());break;
                    case 2:new FrameImaQ(foo,s,re,datoEnc,s.getNextStIQ());break;
                    case 3:new FrameMouseTraking(foo,s,re,datoEnc,s.getNextQG());
                    default:break;
                }
            }else{
                strTemp[0]="Gracias por Participar";strTemp[1]="Write your Answer";
                strTemp[2]="Schreiben Sie Ihre Antwort";strTemp[3]="Ecrivez votre réponse";
                JOptionPane.showMessageDialog(null,strTemp[foo]);
                new PanelMiembro(foo);
            }
            this.dispose();
        }
    }
    
    public void menuCharger(){
    menuBar=new JMenuBar();
    menu = new JMenu();
    strTemp[0]="Idioma";strTemp[1]="Language";strTemp[2]="Sprache";strTemp[3]="langue";
    menu.setText(strTemp[foo]);
    menuBar.add(Box.createHorizontalGlue());
    menuBar.add(menu);
    strTemp[0]="Selecciona tu idioma";strTemp[1]="Select your language";strTemp[2]="Wählen Sie Ihre Sprache";strTemp[3]="Choisissez votre langue";
    menuItem = new JMenuItem(strTemp[foo]);
    menuItem.setEnabled(false);
    menu.add(menuItem);
    menu.addSeparator();
    rbMILang= new JRadioButtonMenuItem[4];
    rbMILang[0]= new JRadioButtonMenuItem("Español");
    rbMILang[1]= new JRadioButtonMenuItem("English");
    rbMILang[2]= new JRadioButtonMenuItem("Deutsh");
    rbMILang[3]= new JRadioButtonMenuItem("Française");
    rbMILang[foo].setSelected(true);
    menu.addSeparator();
    for(int i=0;i<4;i++){
        menu.add(rbMILang[i]);
        rbMILang[i].addActionListener(this);//
    }
    this.setJMenuBar(menuBar);
        //this.add(menuBar);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jlAsk;
    private javax.swing.JLabel jlNumAsk;
    private MouseTraking jpMouseT;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        for(int i=0;i<4;i++){
            if(e.getSource()==rbMILang[i]){
                for(int j=0;j<4;j++){
                    rbMILang[j].setSelected(false);
                }
                rbMILang[i].setSelected(true);
                setIdioma(i);
            }
        }
    }
}
