/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz.FrameEncuestas;

import estructuras.*;
import interfaz.JPanelConFondo;
import javax.swing.WindowConstants;

/**
 *
 * @author Shadow
 */
public class FrameImaQ extends javax.swing.JFrame {

    private int foo;
    private String strTemp[]=new String[4];
    
    private Survey s;
    private RespEnq re;
    
    public FrameImaQ(int foo,Survey s,RespEnq re){
        this.foo=foo;
        this.s=s;
        this.re=re;
        
        //setTitle(s.getName());
        setTitle("Name Enc");
        initComponents();
        
        setDefaultCloseOperation (WindowConstants.EXIT_ON_CLOSE);
        setLocation(10,20);
        setSize(410, 500);
        setVisible (true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rbGroup = new javax.swing.ButtonGroup();
        jlNumAsk = new javax.swing.JLabel();
        jlAsk = new javax.swing.JLabel();
        jpIma1 = new JPanelConFondo("../ima/cuadricula.png");
        jpIma2 = new JPanelConFondo("../ima/cuadricula.png");
        jpIma3 = new JPanelConFondo("../ima/cuadricula.png");
        jpIma4 = new JPanelConFondo("../ima/cuadricula.png");
        jbNext = new javax.swing.JButton();
        jrbIma1 = new javax.swing.JRadioButton();
        jrbIma2 = new javax.swing.JRadioButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jrbIma4 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlNumAsk.setText("jLabel2");
        getContentPane().add(jlNumAsk, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jlAsk.setText("jLabel2");
        getContentPane().add(jlAsk, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        javax.swing.GroupLayout jpIma1Layout = new javax.swing.GroupLayout(jpIma1);
        jpIma1.setLayout(jpIma1Layout);
        jpIma1Layout.setHorizontalGroup(
            jpIma1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );
        jpIma1Layout.setVerticalGroup(
            jpIma1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );

        getContentPane().add(jpIma1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 140, 140));

        javax.swing.GroupLayout jpIma2Layout = new javax.swing.GroupLayout(jpIma2);
        jpIma2.setLayout(jpIma2Layout);
        jpIma2Layout.setHorizontalGroup(
            jpIma2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );
        jpIma2Layout.setVerticalGroup(
            jpIma2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );

        getContentPane().add(jpIma2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, 140, 140));

        javax.swing.GroupLayout jpIma3Layout = new javax.swing.GroupLayout(jpIma3);
        jpIma3.setLayout(jpIma3Layout);
        jpIma3Layout.setHorizontalGroup(
            jpIma3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );
        jpIma3Layout.setVerticalGroup(
            jpIma3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );

        getContentPane().add(jpIma3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 140, 140));

        javax.swing.GroupLayout jpIma4Layout = new javax.swing.GroupLayout(jpIma4);
        jpIma4.setLayout(jpIma4Layout);
        jpIma4Layout.setHorizontalGroup(
            jpIma4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );
        jpIma4Layout.setVerticalGroup(
            jpIma4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );

        getContentPane().add(jpIma4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, -1, -1));

        strTemp[0]="Siguiente";strTemp[1]="Next";strTemp[2]="Nächste";strTemp[3]="Prochain";
        jbNext.setText(strTemp[foo]);
        getContentPane().add(jbNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 420, -1, -1));

        jrbIma1.setText("1");
        getContentPane().add(jrbIma1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, -1, -1));

        jrbIma2.setText("2");
        getContentPane().add(jrbIma2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, -1, -1));

        jRadioButton1.setText("3");
        getContentPane().add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, -1, 20));

        jrbIma4.setText("4");
        getContentPane().add(jrbIma4, new org.netbeans.lib.awtextra.AbsoluteConstraints(283, 380, 80, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JButton jbNext;
    private javax.swing.JLabel jlAsk;
    private javax.swing.JLabel jlNumAsk;
    private javax.swing.JPanel jpIma1;
    private javax.swing.JPanel jpIma2;
    private javax.swing.JPanel jpIma3;
    private javax.swing.JPanel jpIma4;
    private javax.swing.JRadioButton jrbIma1;
    private javax.swing.JRadioButton jrbIma2;
    private javax.swing.JRadioButton jrbIma4;
    private javax.swing.ButtonGroup rbGroup;
    // End of variables declaration//GEN-END:variables
}
