/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz.FrameEncuestas;

import estructuras.*;
import javax.swing.JPanel;
import javax.swing.WindowConstants;

/**
 *
 * @author Shadow
 */
public class FrameMouseTraking extends javax.swing.JFrame {

    
    private int foo;
    private String strTemp[]=new String[4];
    
    private Survey s;
    private RespEnq re;
    
    public FrameMouseTraking(int foo,Survey s,RespEnq re){
        this.foo=foo;
        this.s=s;
        this.re=re;
        
        setTitle(s.getName());
        initComponents();
        
        setDefaultCloseOperation (WindowConstants.EXIT_ON_CLOSE);
        setLocation(10,20);
        setSize(700, 620);
        setVisible (true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jpMouseT = new MouseTraking("../../ima/cuadricula.png");
        jlAsk = new javax.swing.JLabel();
        jlNumAsk = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        //new MouseTraking1(s.getNextQG().getDir());
        jpMouseT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nextSurvey();
            }
        });
        jpMouseT.setPreferredSize(new java.awt.Dimension(650, 500));

        javax.swing.GroupLayout jpMouseTLayout = new javax.swing.GroupLayout(jpMouseT);
        jpMouseT.setLayout(jpMouseTLayout);
        jpMouseTLayout.setHorizontalGroup(
            jpMouseTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );
        jpMouseTLayout.setVerticalGroup(
            jpMouseTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        getContentPane().add(jpMouseT, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 650, 500));

        jlAsk.setText(s.getNextQG().getQuest(foo));
        getContentPane().add(jlAsk, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jlNumAsk.setText(""/*s.getActual()+1*/);
        getContentPane().add(jlNumAsk, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void nextSurvey(){
        if(!((MouseTraking)jpMouseT).isEmpty()){
            re.setSIT(((MouseTraking)jpMouseT).getPoints(),
                    ((MouseTraking)jpMouseT).getClick());
            switch(s.getNext()){
                case 0:/*new FrameAskFree(0,s,re)*/;break;
                case 1:new FrameLikeIt(0,s,re);break;
                case 2:new FrameImaQ(0,s,re);break;
                case 3:new FrameMouseTraking(0,s,re);
                default:break;
            }
            this.dispose();
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jlAsk;
    private javax.swing.JLabel jlNumAsk;
    private javax.swing.JPanel jpMouseT;
    // End of variables declaration//GEN-END:variables
}
